team_index:
    path:     /
    defaults: { _controller: "GameFrontBundle:Team:index" }
    methods:  GET

team_show:
    path:     /{teamId}/show
    defaults: { _controller: "GameFrontBundle:Team:show" }
    methods:  GET

team_new:
    path:     /new
    defaults: { _controller: "GameFrontBundle:Team:new" }
    methods:  [GET, POST]

team_edit:
    path:     /{teamId}/edit
    defaults: { _controller: "GameFrontBundle:Team:edit" }
    methods:  [GET, POST]

team_delete:
    path:     /{teamId}/delete
    defaults: { _controller: "GameFrontBundle:Team:delete" }
    methods:  DELETE
