<?php

namespace GameFrontBundle\Repository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

class TeamRepository extends EntityRepository
{
    public function findTeam(){
        $q=$this->getEntityManager()
            ->createQuery('SELECT t,g FROM GameFrontBundle:Team as t INNER JOIN GameFrontBundle:Game as g WITH t.game = g.gameId');
        return $q->getResult();

    }
}
